
[functions.analyze-productivity]
verify_jwt = true

[functions.process-payment]
verify_jwt = false

[functions.check-paypal-config]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

