import { GoogleGenerativeAI } from "@google/generative-ai";
import { toast } from "sonner";
import { extractPageContent } from "./contentExtractor";
import { Language } from "@/stores/languageStore";

// Mock responses for development mode
const MOCK_RESPONSES = {
  chat: "This is a mock response for development mode. In production, this would be generated by Gemini AI.",
  summary: "This is a mock summary for development mode.",
  category: "Development",
};

const getGeminiModel = async () => {
  try {
    if (typeof chrome === 'undefined' || !chrome.identity) {
      console.log('Running in development mode - using mock Gemini responses');
      return null;
    }

    const { token } = await chrome.identity.getAuthToken({ interactive: true });
    if (!token) {
      throw new Error("Failed to get auth token");
    }

    const genAI = new GoogleGenerativeAI(token);
    const model = genAI.getGenerativeModel({ model: "gemini-pro" });
    return model;
  } catch (error) {
    console.error("Error getting Gemini model:", error);
    throw error;
  }
};

export const summarizeContent = async (prompt: string, language: Language): Promise<string> => {
  try {
    const model = await getGeminiModel();
    if (!model) {
      // Return mock response in development mode
      return `[DEV MODE] ${MOCK_RESPONSES.chat} (Language: ${language.name})`;
    }

    const result = await model.generateContent(
      `Summarize this content in ${language.name} (${language.nativeName}). Focus on the main points and key information: ${prompt}`
    );
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error('Error summarizing content:', error);
    toast.error("Failed to generate summary");
    throw error;
  }
};

export const suggestBookmarkCategory = async (title: string, url: string): Promise<string> => {
  try {
    const model = await getGeminiModel();
    if (!model) {
      // Return mock category in development mode
      return MOCK_RESPONSES.category;
    }

    const prompt = `Given this bookmark with title "${title}" and URL "${url}", suggest a single word category for it. Only respond with the category word, nothing else.`;
    
    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text().trim();
  } catch (error) {
    console.error('Error suggesting category:', error);
    toast.error("Failed to suggest category");
    throw error;
  }
};

export const summarizeBookmark = async (bookmark: { title: string; url?: string }, language: Language): Promise<string> => {
  try {
    const model = await getGeminiModel();
    if (!model) {
      // Return mock summary in development mode
      return `[DEV MODE] ${MOCK_RESPONSES.summary} (Language: ${language.name})`;
    }

    let content = `Title: ${bookmark.title}\n`;
    
    if (bookmark.url) {
      toast.loading("Fetching webpage content...");
      const pageContent = await extractPageContent(bookmark.url);
      content += `\nContent:\n${pageContent}`;
    }
    
    toast.loading("Generating summary...");
    return await summarizeContent(content, language);
  } catch (error) {
    console.error('Error summarizing bookmark:', error);
    toast.error("Failed to summarize bookmark");
    throw error;
  }
};