// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkpgkogqxnamvlptxhat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrcGdrb2dxeG5hbXZscHR4aGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MjkxNzgsImV4cCI6MjA1NTUwNTE3OH0.LebUJNQy2LoZZytuXnbdG7MB25hfht1CYKZHSFhgd7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);