
name: Deploy to Firebase and Supabase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        
      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Update PayPal Configuration in Supabase
        run: |
          curl -X POST "https://hkpgkogqxnamvlptxhat.supabase.co/rest/v1/app_configuration" \
            -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "key": "paypal", 
              "value": {
                "client_id": "${{ secrets.PAYPAL_CLIENT_ID }}",
                "client_secret": "${{ secrets.PAYPAL_SECRET_KEY }}",
                "mode": "live"
              }
            }'
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
          PAYPAL_SECRET_KEY: ${{ secrets.PAYPAL_SECRET_KEY }}

      - name: Deploy to Firebase
        run: firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
