
name: Deploy to Firebase and Local Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        
      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Update PayPal Configuration in Local Storage
        run: |
          echo "PayPal configuration set in local storage"
        env:
          PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
          PAYPAL_SECRET_KEY: ${{ secrets.PAYPAL_SECRET_KEY }}

      - name: Deploy to Firebase
        run: firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
